# Generated by Django 4.1.2 on 2023-01-03 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='shared_conter',
            new_name='shared_counter',
        ),
    ]
